import gi
import math
import os
import subprocess
import tempfile
from pathlib import Path

gi.require_version("Gtk", "3.0")
gi.require_version("Gdk", "3.0")
gi.require_version("GdkX11", "3.0")
gi.require_version("Pango", "1.0")
gi.require_version("PangoCairo", "1.0")
gi.require_version("Vte", "2.91")

from gi.repository import Gdk, GdkX11, GLib, Gtk, Pango, PangoCairo, Vte

from .window_registry import WindowRegistry
from .x11 import run_command


MIN_TILE_WIDTH = 24
MAX_TILE_WIDTH = 960
MIN_TILE_HEIGHT = 18
MAX_TILE_HEIGHT = 640
SHRINK_TILE_WIDTH = 1
SHRINK_TILE_HEIGHT = 1
DEFAULT_TILE_WIDTH = 120
DEFAULT_TILE_HEIGHT = 72
WINDOW_REFRESH_MS = 1800
ACTIVE_WINDOW_POLL_MS = 500
ORDER_MODES = {"manual", "name", "last-used"}
LABEL_MODES = {"title", "app"}
IDLE_MODES = {"off", "collapse", "hide"}
CLOCK_MODES = {"time", "time-seconds", "date-time", "full"}
TINT2_PROFILES = {"default", "chema-compact"}
TINT2_SLOT_UNITS = 2
HOVER_MODES = {
    "off": 1.0,
    "soft": 1.08,
    "medium": 1.18,
    "large": 1.32,
}
MIN_HOVER_SCALE = 1.0
MAX_HOVER_SCALE = 2.5


def clamp(value, lower, upper, fallback):
    try:
        value = int(value)
    except (TypeError, ValueError):
        return fallback
    return max(lower, min(upper, value))


def refresh_interval_ms(fps):
    try:
        fps = float(fps)
    except (TypeError, ValueError):
        fps = 1.0
    if fps <= 0:
        return None
    return max(100, int(round(1000.0 / fps)))


def interval_seconds_to_ms(seconds):
    try:
        seconds = float(seconds)
    except (TypeError, ValueError):
        return None
    if seconds <= 0:
        return None
    return max(100, int(round(seconds * 1000.0)))


def normalize_hover_mode(mode, hover_expand=False):
    if mode in HOVER_MODES:
        return mode
    return "medium" if hover_expand else "off"


def normalize_hover_scale(value, mode=None, hover_expand=False):
    try:
        value = float(value)
    except (TypeError, ValueError):
        value = HOVER_MODES[normalize_hover_mode(mode, hover_expand)]
    return max(MIN_HOVER_SCALE, min(MAX_HOVER_SCALE, value))


def normalize_order_mode(value):
    return value if value in ORDER_MODES else "last-used"


def normalize_label_mode(value):
    return value if value in LABEL_MODES else "title"


def normalize_idle_mode(value):
    return value if value in IDLE_MODES else "off"


def normalize_clock_mode(value):
    return value if value in CLOCK_MODES else "date-time"


def normalize_tint2_profile(value):
    return value if value in TINT2_PROFILES else "default"


def read_current_tint2_launchers():
    candidates = [
        Path.home() / ".config" / "tint2" / "tint2-sessionfile",
        Path.home() / ".config" / "tint2" / "tint2rc",
    ]
    launchers = []
    seen = set()
    for path in candidates:
        if not path.exists():
            continue
        try:
            for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
                stripped = line.strip()
                if not stripped.startswith("launcher_item_app"):
                    continue
                _key, _sep, value = stripped.partition("=")
                launcher_path = Path(os.path.expanduser(value.strip()))
                if launcher_path.is_absolute() and not launcher_path.exists():
                    continue
                if stripped in seen:
                    continue
                seen.add(stripped)
                launchers.append(stripped)
        except OSError:
            continue
        if launchers:
            break
    return launchers


def build_tint2_config(profile):
    profile = normalize_tint2_profile(profile)
    launcher_lines = []
    panel_items = "T"
    taskbar_lines = [
        "taskbar_mode = multi_desktop",
        "taskbar_hide_if_empty = 0",
        "task_icon = 1",
        "task_text = 0",
        "task_maximum_size = 24 24",
        "task_padding = 1 1 1",
    ]
    if profile == "chema-compact":
        launcher_lines = read_current_tint2_launchers()
        panel_items = "L" if launcher_lines else "T"
        taskbar_lines = [
            "taskbar_mode = multi_desktop",
            "taskbar_hide_if_empty = 1",
            "task_icon = 1",
            "task_text = 0",
            "task_maximum_size = 20 20",
            "task_padding = 0 0 0",
        ]

    launcher_block = "\n".join(launcher_lines)
    if launcher_block:
        launcher_block += "\n"
    taskbar_block = "\n".join(taskbar_lines)

    return f"""# Generated by winmirror-launcher. Edit your main tint2 panel, not this temp file.
rounded = 0
border_width = 0
background_color = #111111 92
border_color = #000000 0

rounded = 0
border_width = 1
background_color = #20242a 100
border_color = #404852 100

panel_monitor = primary
panel_position = top left horizontal
panel_size = 240 48
panel_margin = 0 0
panel_padding = 1 1 1
panel_background_id = 1
panel_items = {panel_items}
panel_window_name = winmirror-launcher-tint2
panel_layer = top
panel_dock = 0
strut_policy = none
wm_menu = 0
disable_transparency = 1
mouse_effects = 0

launcher_padding = 1 1 1
launcher_background_id = 0
launcher_icon_background_id = 0
launcher_icon_size = 20
{launcher_block}
taskbar_padding = 1 1 1
taskbar_background_id = 0
taskbar_active_background_id = 0
{taskbar_block}
task_background_id = 0
task_active_background_id = 0
task_urgent_background_id = 0
task_iconified_background_id = 0
task_font = Sans 7
task_font_color = #dddddd 100
task_active_font_color = #ffffff 100
task_urgent_font_color = #ffffff 100
task_icon_asb = 100 0 0
task_active_icon_asb = 100 0 0
task_urgent_icon_asb = 100 0 0
task_iconified_icon_asb = 75 0 0

tooltip = 0
"""


def app_name_from_wm_class(wm_class):
    value = (wm_class or "").strip()
    if not value:
        return "app"
    return value.split(".")[-1] or value


class LooseFixed(Gtk.Fixed):
    __gtype_name__ = "WinmirrorLooseFixed"

    def do_get_preferred_width(self):
        return 1, 1

    def do_get_preferred_height(self):
        return 1, 1

    def do_get_preferred_width_for_height(self, _height):
        return 1, 1

    def do_get_preferred_height_for_width(self, _width):
        return 1, 1


class ClockSlot(Gtk.DrawingArea):
    def __init__(self, mode="date-time"):
        super().__init__()
        self.mode = normalize_clock_mode(mode)
        self.set_size_request(DEFAULT_TILE_WIDTH, DEFAULT_TILE_HEIGHT)
        self.connect("draw", self.on_draw)

    def set_mode(self, mode):
        self.mode = normalize_clock_mode(mode)
        self.queue_draw()

    def format_lines(self):
        now = GLib.DateTime.new_now_local()
        if self.mode == "time":
            return [now.format("%H:%M")]
        if self.mode == "time-seconds":
            return [now.format("%H:%M:%S")]
        if self.mode == "full":
            return [now.format("%A"), now.format("%d/%m/%Y"), now.format("%H:%M:%S")]
        return [now.format("%d/%m/%Y"), now.format("%H:%M")]

    def on_draw(self, widget, cr):
        alloc = widget.get_allocation()
        width = max(1, alloc.width)
        height = max(1, alloc.height)
        cr.set_source_rgb(0.03, 0.035, 0.04)
        cr.rectangle(0, 0, width, height)
        cr.fill()
        cr.set_source_rgb(0.18, 0.18, 0.18)
        cr.set_line_width(1.0)
        cr.rectangle(0.5, 0.5, max(0, width - 1), max(0, height - 1))
        cr.stroke()

        lines = self.format_lines()
        font = "Sans Bold 12" if len(lines) == 1 else "Sans Bold 9"
        layouts = []
        total_height = 0
        for line in lines:
            layout = widget.create_pango_layout(line)
            layout.set_font_description(Pango.FontDescription(font))
            layout.set_ellipsize(Pango.EllipsizeMode.END)
            layout.set_width(max(1, width - 10) * Pango.SCALE)
            _tw, th = layout.get_pixel_size()
            layouts.append((layout, th))
            total_height += th
        total_height += max(0, len(lines) - 1) * 2
        y = max(2, (height - total_height) / 2.0)
        cr.set_source_rgb(0.9, 0.92, 0.94)
        for layout, th in layouts:
            tw, _th = layout.get_pixel_size()
            cr.move_to(max(5, (width - tw) / 2.0), y)
            PangoCairo.show_layout(cr, layout)
            y += th + 2
        return False


class MiniTerminalSlot(Gtk.Box):
    def __init__(self, shell=None):
        super().__init__(orientation=Gtk.Orientation.VERTICAL, spacing=0)
        self.shell = shell or os.environ.get("SHELL") or "/bin/sh"
        self.set_size_request(DEFAULT_TILE_WIDTH, DEFAULT_TILE_HEIGHT)
        self.terminal = Vte.Terminal()
        self.terminal.set_scrollback_lines(300)
        self.terminal.set_size(24, 6)
        self.pack_start(self.terminal, True, True, 0)
        self.spawn_shell()

    def spawn_shell(self):
        argv = [self.shell]
        try:
            self.terminal.spawn_async(
                Vte.PtyFlags.DEFAULT,
                os.path.expanduser("~"),
                argv,
                None,
                GLib.SpawnFlags.DEFAULT,
                None,
                None,
                -1,
                None,
                None,
                None,
            )
        except TypeError:
            self.terminal.spawn_async(
                Vte.PtyFlags.DEFAULT,
                os.path.expanduser("~"),
                argv,
                None,
                GLib.SpawnFlags.DEFAULT,
                None,
                -1,
                None,
                None,
                None,
            )


class CommandRunnerSlot(Gtk.Box):
    def __init__(self):
        super().__init__(orientation=Gtk.Orientation.VERTICAL, spacing=0)
        self.set_size_request(DEFAULT_TILE_WIDTH, DEFAULT_TILE_HEIGHT)
        self.set_border_width(2)
        self.set_halign(Gtk.Align.FILL)
        self.set_valign(Gtk.Align.FILL)

        self.entry = Gtk.Entry()
        self.entry.set_placeholder_text("Ejecutar")
        self.entry.set_width_chars(1)
        self.entry.set_max_width_chars(16)
        self.entry.set_hexpand(True)
        self.entry.set_size_request(1, 24)
        self.entry.connect("activate", self.on_activate)
        self.pack_start(self.entry, True, False, 0)

        self.status = Gtk.Label(label="")
        self.status.set_no_show_all(True)

    def on_activate(self, entry):
        command = (entry.get_text() or "").strip()
        if not command:
            return True
        try:
            subprocess.Popen(
                ["/bin/sh", "-lc", command],
                cwd=os.path.expanduser("~"),
                start_new_session=True,
            )
        except OSError as exc:
            self.status.set_text(str(exc))
            return True
        self.status.set_text(command)
        entry.set_text("")
        return True


class Tint2Slot(Gtk.Box):
    def __init__(self, profile="default"):
        super().__init__(orientation=Gtk.Orientation.VERTICAL, spacing=0)
        self.profile = normalize_tint2_profile(profile)
        self.process = None
        self.config_path = None
        self.move_source_id = None
        self.target_rect = None
        self.window_id = None
        self.set_size_request(DEFAULT_TILE_WIDTH * TINT2_SLOT_UNITS, DEFAULT_TILE_HEIGHT)

        self.label = Gtk.Label(label="tint2")
        self.label.set_xalign(0.5)
        self.label.set_yalign(0.5)
        self.pack_start(self.label, True, True, 0)

    def set_profile(self, profile):
        self.profile = normalize_tint2_profile(profile)
        self.restart()

    def start(self):
        if self.process is not None and self.process.poll() is None:
            return
        if subprocess.run(["/bin/sh", "-lc", "command -v tint2"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode != 0:
            self.label.set_text("tint2 no encontrado")
            return
        self.write_config()
        try:
            self.process = subprocess.Popen(
                ["tint2", "-c", str(self.config_path)],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                start_new_session=True,
            )
        except OSError as exc:
            self.label.set_text(str(exc))
            self.process = None
            return
        self.label.set_text("tint2")
        self.schedule_move()

    def write_config(self):
        if self.config_path is None:
            handle = tempfile.NamedTemporaryFile("w", encoding="utf-8", prefix="winmirror-tint2-", suffix=".tint2rc", delete=False)
            self.config_path = Path(handle.name)
        else:
            handle = self.config_path.open("w", encoding="utf-8")
        with handle:
            handle.write(build_tint2_config(self.profile))

    def restart(self):
        was_running = self.process is not None and self.process.poll() is None
        self.stop()
        if was_running or self.get_visible():
            self.start()

    def stop(self):
        if self.move_source_id is not None:
            GLib.source_remove(self.move_source_id)
            self.move_source_id = None
        if self.process is not None and self.process.poll() is None:
            self.process.terminate()
            try:
                self.process.wait(timeout=1.0)
            except subprocess.TimeoutExpired:
                self.process.kill()
        self.process = None
        self.window_id = None
        if self.config_path is not None:
            try:
                self.config_path.unlink()
            except OSError:
                pass
            self.config_path = None

    def set_target_rect(self, x, y, width, height):
        self.target_rect = (int(x), int(y), max(1, int(width)), max(1, int(height)))
        self.schedule_move()

    def schedule_move(self):
        if self.move_source_id is None:
            self.move_source_id = GLib.timeout_add(120, self.move_tint2_window)

    def move_tint2_window(self):
        self.move_source_id = None
        if self.process is None or self.process.poll() is not None or self.target_rect is None:
            return False
        window_id = self.window_id or self.find_tint2_window_id()
        if window_id is None:
            self.schedule_move()
            return False
        x, y, width, height = self.target_rect
        subprocess.run(
            ["wmctrl", "-ir", window_id, "-b", "add,skip_taskbar,skip_pager,above"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        subprocess.run(
            ["wmctrl", "-ir", window_id, "-e", f"0,{x},{y},{width},{height}"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        return False

    def find_tint2_window_id(self):
        if self.process is None:
            return None
        proc = subprocess.run(["wmctrl", "-lp"], text=True, capture_output=True, check=False)
        if proc.returncode != 0:
            return None
        pid = str(self.process.pid)
        for line in proc.stdout.splitlines():
            parts = line.split(None, 4)
            if len(parts) >= 3 and parts[2] == pid:
                self.window_id = parts[0]
                return self.window_id
        return None


class SimpleMirrorTile(Gtk.DrawingArea):
    def __init__(
        self,
        window_info,
        width=DEFAULT_TILE_WIDTH,
        height=DEFAULT_TILE_HEIGHT,
        fps=1.0,
        frame_interval_seconds=None,
        show_title=False,
        show_close=False,
        show_workspace=False,
        hover_expand=False,
        hover_mode=None,
        hover_scale=None,
        show_borders=False,
        label_mode="title",
        panel=None,
    ):
        super().__init__()
        self.panel = panel
        self.window_info = window_info
        self.tile_width = clamp(width, MIN_TILE_WIDTH, MAX_TILE_WIDTH, DEFAULT_TILE_WIDTH)
        self.tile_height = clamp(height, MIN_TILE_HEIGHT, MAX_TILE_HEIGHT, DEFAULT_TILE_HEIGHT)
        self.hover_mode = normalize_hover_mode(hover_mode, hover_expand)
        self.hover_scale = normalize_hover_scale(hover_scale, self.hover_mode, hover_expand)
        self.interval_ms = interval_seconds_to_ms(frame_interval_seconds) or refresh_interval_ms(fps)
        self.source_window = None
        self.current_pixbuf = None
        self.status = ""
        self.show_title = bool(show_title)
        self.show_close = bool(show_close)
        self.show_workspace = bool(show_workspace)
        self.hover_expand = self.hover_mode != "off"
        self.show_borders = bool(show_borders)
        self.label_mode = normalize_label_mode(label_mode)
        self.hovered = False
        self.dragging = False
        self.refresh_source_id = None
        self.layout_width = self.tile_width
        self.layout_height = self.tile_height

        self.set_hexpand(True)
        self.set_vexpand(True)
        self.set_layout_size(self.layout_width, self.layout_height)
        self.set_tooltip_text(window_info.title)
        self.add_events(
            Gdk.EventMask.BUTTON_PRESS_MASK
            | Gdk.EventMask.ENTER_NOTIFY_MASK
            | Gdk.EventMask.LEAVE_NOTIFY_MASK
        )
        self.connect("draw", self.on_draw)
        self.connect("button-press-event", self.on_button_press)
        self.connect("enter-notify-event", self.on_enter)
        self.connect("leave-notify-event", self.on_leave)
        self.connect("destroy", self.on_destroy)

        self.attach_source()
        self.set_refresh_interval(self.interval_ms)
        self.refresh()

    def on_destroy(self, *_args):
        if self.refresh_source_id is not None:
            GLib.source_remove(self.refresh_source_id)
            self.refresh_source_id = None

    def set_fps(self, fps):
        self.set_refresh_interval(refresh_interval_ms(fps))

    def set_frame_interval_seconds(self, seconds):
        self.set_refresh_interval(interval_seconds_to_ms(seconds))

    def set_refresh_interval(self, interval_ms):
        self.interval_ms = interval_ms
        if self.refresh_source_id is not None:
            GLib.source_remove(self.refresh_source_id)
            self.refresh_source_id = None
        if self.interval_ms is not None:
            self.refresh_source_id = GLib.timeout_add(self.interval_ms, self.refresh)

    def set_dimensions(self, width, height):
        self.tile_width = clamp(width, MIN_TILE_WIDTH, MAX_TILE_WIDTH, DEFAULT_TILE_WIDTH)
        self.tile_height = clamp(height, MIN_TILE_HEIGHT, MAX_TILE_HEIGHT, DEFAULT_TILE_HEIGHT)
        if self.panel is None:
            self.set_layout_size(self.tile_width, self.tile_height)
        self.queue_resize()
        self.queue_draw()

    def set_layout_size(self, width, height):
        self.layout_width = max(1, int(round(width)))
        self.layout_height = max(1, int(round(height)))
        self.set_size_request(self.layout_width, self.layout_height)

    def release_layout_size(self):
        self.layout_width = SHRINK_TILE_WIDTH
        self.layout_height = SHRINK_TILE_HEIGHT
        self.set_size_request(SHRINK_TILE_WIDTH, SHRINK_TILE_HEIGHT)

    def set_display_options(
        self,
        show_title=None,
        show_close=None,
        show_workspace=None,
        hover_expand=None,
        hover_mode=None,
        hover_scale=None,
        show_borders=None,
        label_mode=None,
    ):
        if show_title is not None:
            self.show_title = bool(show_title)
        if show_close is not None:
            self.show_close = bool(show_close)
        if show_workspace is not None:
            self.show_workspace = bool(show_workspace)
        if hover_mode is not None or hover_expand is not None:
            self.hover_mode = normalize_hover_mode(hover_mode, hover_expand if hover_expand is not None else self.hover_expand)
            self.hover_expand = self.hover_mode != "off"
            if hover_scale is None:
                self.hover_scale = normalize_hover_scale(None, self.hover_mode, self.hover_expand)
        if hover_scale is not None:
            self.hover_scale = normalize_hover_scale(hover_scale, self.hover_mode, self.hover_expand)
            self.hover_expand = self.hover_scale > 1.0
            if self.hover_scale <= 1.0:
                self.hover_mode = "off"
        if show_borders is not None:
            self.show_borders = bool(show_borders)
        if label_mode is not None:
            self.label_mode = normalize_label_mode(label_mode)
        self.set_dimensions(self.tile_width, self.tile_height)

    def display_name(self):
        if self.label_mode == "app":
            return app_name_from_wm_class(self.window_info.wm_class)
        return self.window_info.title or app_name_from_wm_class(self.window_info.wm_class)

    def attach_source(self):
        display = Gdk.Display.get_default()
        if display is None:
            self.status = "sin display"
            return False
        try:
            self.source_window = GdkX11.X11Window.foreign_new_for_display(
                display,
                int(self.window_info.window_id),
            )
        except (TypeError, ValueError):
            self.source_window = None
        if self.source_window is None:
            self.status = "cerrada"
            return False
        return True

    def is_viewable(self):
        proc = run_command(["xwininfo", "-id", str(int(self.window_info.window_id))])
        if proc is None or proc.returncode != 0:
            self.status = "cerrada"
            return False
        if "Map State: IsViewable" not in proc.stdout:
            self.status = "oculta"
            return False
        return True

    def refresh(self):
        if self.source_window is None and not self.attach_source():
            self.current_pixbuf = None
            self.queue_draw()
            return True

        if not self.is_viewable():
            if self.status == "cerrada":
                self.current_pixbuf = None
            self.queue_draw()
            return True

        width = max(1, self.source_window.get_width())
        height = max(1, self.source_window.get_height())
        if width <= 1 or height <= 1:
            self.status = "sin imagen"
            self.queue_draw()
            return True

        Gdk.error_trap_push()
        pixbuf = Gdk.pixbuf_get_from_window(self.source_window, 0, 0, width, height)
        Gdk.flush()
        error = Gdk.error_trap_pop()
        if error:
            self.status = "sin imagen"
            self.source_window = None
            self.queue_draw()
            return True
        if pixbuf is None:
            self.status = "sin imagen"
        else:
            self.status = ""
            self.current_pixbuf = pixbuf
        self.queue_draw()
        return True

    def activate_window(self):
        window_id = str(int(self.window_info.window_id))
        proc = run_command(["xdotool", "windowactivate", "--sync", window_id])
        if proc is not None and proc.returncode == 0:
            if self.panel is not None:
                self.panel.note_window_used(self.window_info.window_id)
            return True
        proc = run_command(["wmctrl", "-ia", self.window_info.window_hex])
        activated = proc is not None and proc.returncode == 0
        if activated and self.panel is not None:
            self.panel.note_window_used(self.window_info.window_id)
        return activated

    def close_window(self):
        proc = run_command(["wmctrl", "-ic", self.window_info.window_hex])
        return proc is not None and proc.returncode == 0

    def on_button_press(self, _widget, event):
        if int(event.button) == 3 and self.panel is not None:
            self.panel.show_context_menu(event, self)
            return True
        if self.panel is not None and self.panel.order_edit_mode and int(event.button) == 1:
            if self.handle_order_edit_click(event):
                return True
        alloc = self.get_allocation()
        if self.show_close and int(event.button) == 1:
            if event.x >= alloc.width - 18 and event.y <= 18:
                self.close_window()
                return True
        if int(event.button) == 1:
            self.activate_window()
            return True
        if int(event.button) == 2:
            self.close_window()
            return True
        return False

    def handle_order_edit_click(self, event):
        alloc = self.get_allocation()
        width = max(1, alloc.width)
        height = max(1, alloc.height)
        control_size = max(16, min(28, min(width, height) // 3))
        if event.y <= control_size:
            if event.x <= control_size:
                self.panel.move_tile(self, -1)
                return True
            if event.x >= width - control_size:
                self.panel.move_tile(self, 1)
                return True
        if event.y >= height - control_size:
            if event.x <= control_size:
                self.panel.move_tile(self, -self.panel.current_columns)
                return True
            if event.x >= width - control_size:
                self.panel.move_tile(self, self.panel.current_columns)
                return True
        return False

    def on_enter(self, *_args):
        self.hovered = True
        if self.panel is not None:
            self.panel.note_pointer_inside(True)
            self.panel.set_hovered_tile(self)
        self.queue_draw()
        return False

    def on_leave(self, *_args):
        self.hovered = False
        if self.panel is not None:
            self.panel.set_hovered_tile(None)
            self.panel.note_pointer_inside(False)
        self.queue_draw()
        return False

    def on_draw(self, widget, cr):
        alloc = widget.get_allocation()
        width = max(1, alloc.width)
        height = max(1, alloc.height)

        cr.set_source_rgb(0.02, 0.02, 0.02)
        cr.rectangle(0, 0, width, height)
        cr.fill()

        if self.current_pixbuf is None:
            self.draw_placeholder(widget, cr, width, height)
            if self.show_borders:
                self.draw_border(cr, width, height)
            return False

        src_w = self.current_pixbuf.get_width()
        src_h = self.current_pixbuf.get_height()
        scale = min(float(width) / src_w, float(height) / src_h)
        draw_w = src_w * scale
        draw_h = src_h * scale
        off_x = (width - draw_w) / 2.0
        off_y = (height - draw_h) / 2.0

        cr.save()
        cr.translate(off_x, off_y)
        cr.scale(scale, scale)
        Gdk.cairo_set_source_pixbuf(cr, self.current_pixbuf, 0, 0)
        cr.paint()
        cr.restore()

        if self.hovered and self.hover_scale > 1.0:
            cr.set_source_rgba(1.0, 1.0, 1.0, min(0.18, 0.04 + ((self.hover_scale - 1.0) * 0.08)))
            cr.rectangle(0, 0, width, height)
            cr.fill()
        if self.show_borders:
            self.draw_border(cr, width, height)
        self.draw_overlays(widget, cr, width, height)
        return False

    def draw_border(self, cr, width, height):
        cr.set_source_rgb(0.18, 0.18, 0.18)
        cr.set_line_width(1.0)
        cr.rectangle(0.5, 0.5, max(0, width - 1), max(0, height - 1))
        cr.stroke()

    def draw_overlays(self, widget, cr, width, height):
        if self.show_workspace:
            self.draw_badge(widget, cr, 3, 2, f"{self.window_info.desktop_index}")

        if self.show_close:
            cr.set_source_rgba(0.0, 0.0, 0.0, 0.65)
            cr.rectangle(width - 18, 0, 18, 18)
            cr.fill()
            layout = widget.create_pango_layout("x")
            layout.set_font_description(Pango.FontDescription("Sans Bold 8"))
            tw, th = layout.get_pixel_size()
            cr.set_source_rgb(0.95, 0.95, 0.95)
            cr.move_to(width - 9 - tw / 2.0, 9 - th / 2.0)
            PangoCairo.show_layout(cr, layout)

        if self.show_title:
            title = self.display_name()[:42]
            layout = widget.create_pango_layout(title)
            layout.set_font_description(Pango.FontDescription("Sans 8"))
            layout.set_ellipsize(Pango.EllipsizeMode.END)
            layout.set_width(max(1, width - 8) * Pango.SCALE)
            _tw, th = layout.get_pixel_size()
            cr.set_source_rgba(0.0, 0.0, 0.0, 0.68)
            cr.rectangle(0, max(0, height - th - 5), width, th + 5)
            cr.fill()
            cr.set_source_rgb(0.92, 0.92, 0.92)
            cr.move_to(4, max(1, height - th - 3))
            PangoCairo.show_layout(cr, layout)

        if self.panel is not None and self.panel.order_edit_mode:
            self.draw_order_controls(widget, cr, width, height)

    def draw_order_controls(self, widget, cr, width, height):
        control_size = max(16, min(28, min(width, height) // 3))
        if width < 24 or height < 18:
            return

        cr.set_source_rgba(0.0, 0.0, 0.0, 0.72)
        for x, y in (
            (0, 0),
            (width - control_size, 0),
            (0, height - control_size),
            (width - control_size, height - control_size),
        ):
            cr.rectangle(x, y, control_size, control_size)
            cr.fill()

        arrows = (
            ("<", 0, 0),
            (">", width - control_size, 0),
            ("^", 0, height - control_size),
            ("v", width - control_size, height - control_size),
        )
        cr.set_source_rgb(0.95, 0.95, 0.95)
        for text, x, y in arrows:
            layout = widget.create_pango_layout(text)
            layout.set_font_description(Pango.FontDescription("Sans Bold 8"))
            tw, th = layout.get_pixel_size()
            cr.move_to(x + (control_size - tw) / 2.0, y + (control_size - th) / 2.0)
            PangoCairo.show_layout(cr, layout)

    def draw_badge(self, widget, cr, x, y, text):
        layout = widget.create_pango_layout(text)
        layout.set_font_description(Pango.FontDescription("Sans Bold 8"))
        tw, th = layout.get_pixel_size()
        cr.set_source_rgba(0.0, 0.0, 0.0, 0.68)
        cr.rectangle(x, y, tw + 8, th + 4)
        cr.fill()
        cr.set_source_rgb(0.9, 0.9, 0.9)
        cr.move_to(x + 4, y + 2)
        PangoCairo.show_layout(cr, layout)

    def draw_placeholder(self, widget, cr, width, height):
        title = self.display_name() or self.window_info.window_hex
        layout = widget.create_pango_layout(title)
        layout.set_font_description(Pango.FontDescription("Sans Bold 8"))
        layout.set_ellipsize(Pango.EllipsizeMode.END)
        layout.set_width(max(1, width - 10) * Pango.SCALE)
        tw, th = layout.get_pixel_size()
        cr.set_source_rgb(0.82, 0.82, 0.82)
        cr.move_to(5, max(4, (height - th) / 2.0 - 5))
        PangoCairo.show_layout(cr, layout)

        if self.status:
            status_layout = widget.create_pango_layout(self.status)
            status_layout.set_font_description(Pango.FontDescription("Sans 7"))
            sw, sh = status_layout.get_pixel_size()
            cr.set_source_rgb(0.55, 0.55, 0.55)
            cr.move_to(max(5, (width - sw) / 2.0), min(height - sh - 3, (height + th) / 2.0 + 1))
            PangoCairo.show_layout(cr, status_layout)


class SimpleLauncherPanel:
    def __init__(
        self,
        windows,
        tile_width=DEFAULT_TILE_WIDTH,
        tile_height=DEFAULT_TILE_HEIGHT,
        fps=1.0,
        title=None,
        show_title=False,
        show_close=False,
        show_workspace=False,
        hover_expand=False,
        hover_mode=None,
        hover_scale=None,
        show_borders=False,
        order_mode="last-used",
        label_mode="title",
        sticky_workspaces=False,
        idle_mode="off",
        idle_delay_ms=700,
        frame_interval_seconds=None,
        excluded_window_ids=None,
        selected_window_ids=None,
        show_clock=False,
        clock_mode="date-time",
        show_tint2=False,
        tint2_profile="default",
        registry=None,
    ):
        self.registry = registry or WindowRegistry()
        self.excluded_window_ids = {int(item) for item in (excluded_window_ids or [])}
        self.own_window_id = None
        self.windows = windows
        self.tile_width = clamp(tile_width, MIN_TILE_WIDTH, MAX_TILE_WIDTH, DEFAULT_TILE_WIDTH)
        self.tile_height = clamp(tile_height, MIN_TILE_HEIGHT, MAX_TILE_HEIGHT, DEFAULT_TILE_HEIGHT)
        self.fps = fps
        self.show_title = bool(show_title)
        self.show_close = bool(show_close)
        self.show_workspace = bool(show_workspace)
        self.hover_mode = normalize_hover_mode(hover_mode, hover_expand)
        self.hover_expand = self.hover_mode != "off"
        self.hover_scale = normalize_hover_scale(hover_scale, self.hover_mode, hover_expand)
        self.show_borders = bool(show_borders)
        self.label_mode = normalize_label_mode(label_mode)
        self.sticky_workspaces = bool(sticky_workspaces)
        self.idle_mode = normalize_idle_mode(idle_mode)
        self.idle_delay_ms = clamp(idle_delay_ms, 100, 5000, 700)
        self.frame_interval_seconds = frame_interval_seconds
        self.selected_window_ids = None if selected_window_ids is None else {int(item) for item in selected_window_ids}
        self.show_clock = bool(show_clock)
        self.clock_mode = normalize_clock_mode(clock_mode)
        self.clock_source_id = None
        self.show_tint2 = bool(show_tint2)
        self.tint2_profile = normalize_tint2_profile(tint2_profile)
        self.window_refresh_source_id = None
        self.active_window_source_id = None
        self.idle_source_id = None
        self.hidden_poll_source_id = None
        self.current_columns = 0
        self.current_rows = 0
        self.order_edit_mode = False
        self.order_mode = normalize_order_mode(order_mode)
        self.mru_window_ids = []
        self.active_window_id = self.registry.get_active_window_id()
        self.hovered_tile = None
        self.filter_query = ""
        self.pointer_inside_panel = False
        self.collapsed = False
        self.hidden_by_idle = False
        self.restore_size = None
        self.restore_rect = None

        self.win = Gtk.Window()
        self.win.set_title(title or "winmirror-launcher")
        self.win.connect("destroy", self.on_destroy)
        self.win.connect("key-press-event", self.on_key_press)
        self.win.set_resizable(True)
        self.win.set_decorated(True)
        self.win.connect("configure-event", self.on_configure_event)
        self.win.add_events(
            Gdk.EventMask.BUTTON_PRESS_MASK
            | Gdk.EventMask.ENTER_NOTIFY_MASK
            | Gdk.EventMask.LEAVE_NOTIFY_MASK
        )
        self.win.connect("button-press-event", self.on_panel_button_press)
        self.win.connect("enter-notify-event", self.on_panel_enter)
        self.win.connect("leave-notify-event", self.on_panel_leave)

        target_width = max(240, min(len(windows) * self.tile_width, 980))
        target_height = max(48, self.tile_height)
        self.win.set_default_size(target_width, target_height)

        self.grid = LooseFixed()
        self.grid.set_hexpand(True)
        self.grid.set_vexpand(True)
        self.win.add(self.grid)

        self.filter_entry = Gtk.SearchEntry()
        self.filter_entry.set_placeholder_text("Filtrar")
        self.filter_entry.set_width_chars(8)
        self.filter_entry.set_hexpand(False)
        self.filter_entry.connect("changed", self.on_filter_changed)
        self.filter_entry.connect("key-press-event", self.on_filter_key_press)

        self.clock_slot = ClockSlot(self.clock_mode)
        self.clock_slot.set_visible(self.show_clock)
        self.tint2_slot = Tint2Slot(self.tint2_profile)
        self.tint2_slot.set_visible(self.show_tint2)
        self.terminal_slots = []
        self.executor_slots = []

        self.tiles = []
        for info in self.filter_windows(windows):
            self.add_tile(info)
        self.grid.put(self.clock_slot, 0, 0)
        self.grid.put(self.tint2_slot, 0, 0)
        self.grid.put(self.filter_entry, 0, 0)

        self.win.show_all()
        self.clock_slot.set_visible(self.show_clock)
        self.tint2_slot.set_visible(self.show_tint2)
        if self.show_tint2:
            self.tint2_slot.start()
        self.capture_own_window_id()
        self.apply_workspace_behavior()
        self.note_window_used(self.active_window_id, apply_order=False)
        self.apply_order()
        self.fit_tiles_to_window()
        GLib.idle_add(self.fit_tiles_to_window)
        self.update_clock_timer()
        self.window_refresh_source_id = GLib.timeout_add(WINDOW_REFRESH_MS, self.reconcile_windows)
        self.active_window_source_id = GLib.timeout_add(ACTIVE_WINDOW_POLL_MS, self.poll_active_window)

    def capture_own_window_id(self):
        gdk_window = self.win.get_window()
        if gdk_window is None:
            return
        try:
            self.own_window_id = int(gdk_window.get_xid())
        except AttributeError:
            self.own_window_id = None

    def apply_workspace_behavior(self):
        if not self.sticky_workspaces or self.own_window_id is None:
            return
        run_command(["wmctrl", "-i", "-r", f"0x{self.own_window_id:x}", "-b", "add,sticky"])

    def filter_windows(self, windows):
        filtered = []
        for info in windows:
            if int(info.window_id) in self.excluded_window_ids:
                continue
            if self.own_window_id is not None and int(info.window_id) == self.own_window_id:
                continue
            filtered.append(info)
        return filtered

    def visible_tiles(self):
        return [tile for tile in self.tiles if self.tile_matches_selection(tile) and self.tile_matches_filter(tile)]

    def utility_slots(self):
        slots = []
        slots.extend(self.terminal_slots)
        slots.extend(self.executor_slots)
        if self.show_clock:
            slots.append(self.clock_slot)
        if self.show_tint2:
            slots.append(self.tint2_slot)
        return slots

    def layout_slot_count(self):
        return sum(units for _widget, units in self.layout_entries())

    def layout_entries(self):
        entries = [(tile, 1) for tile in self.visible_tiles()]
        entries.extend((slot, self.widget_slot_units(slot)) for slot in self.utility_slots())
        entries.append((self.filter_entry, 1))
        return entries

    def widget_slot_units(self, widget):
        return TINT2_SLOT_UNITS if widget is self.tint2_slot else 1

    def iter_layout_positions(self, entries, columns):
        columns = max(1, int(columns))
        cursor = 0
        for widget, units in entries:
            span = max(1, min(int(units), columns))
            column = cursor % columns
            if span > 1 and column + span > columns:
                cursor += columns - column
                column = 0
            yield widget, cursor, span
            cursor += span

    def layout_rows_for_entries(self, entries, columns):
        max_row = 0
        for _widget, index, span in self.iter_layout_positions(entries, columns):
            row = index // max(1, int(columns))
            max_row = max(max_row, row + 1)
        return max(1, max_row)

    def tile_matches_selection(self, tile):
        if self.selected_window_ids is None:
            return True
        return int(tile.window_info.window_id) in self.selected_window_ids

    def tile_matches_filter(self, tile):
        query = self.filter_query.strip().casefold()
        if not query:
            return True
        info = tile.window_info
        haystack = " ".join(
            str(part or "")
            for part in (
                info.title,
                info.wm_class,
                app_name_from_wm_class(info.wm_class),
                info.window_hex,
                info.window_id,
            )
        ).casefold()
        return all(token in haystack for token in query.split())

    def on_filter_changed(self, entry):
        self.filter_query = entry.get_text() or ""
        self.hovered_tile = None
        self.current_columns = 0
        self.current_rows = 0
        self.fit_tiles_to_window()

    def on_filter_key_press(self, entry, event):
        key = Gdk.keyval_name(event.keyval)
        if key == "Escape" and entry.get_text():
            entry.set_text("")
            return True
        return False

    def position_widget_slot(self, widget, index, columns, column_offsets=None, column_widths=None, span=1):
        index = max(0, int(index))
        columns = max(1, int(columns or self.current_columns or self.layout_slot_count()))
        span = max(1, min(int(span), columns))
        column = index % columns
        row = index // columns
        if column_offsets is not None and column_widths is not None:
            x = column_offsets[column]
            width = sum(column_widths[column : min(columns, column + span)])
        else:
            x = column * self.tile_width
            width = self.tile_width * span
        widget.set_size_request(max(1, int(width)), max(1, int(self.tile_height)))
        self.grid.move(widget, int(x), int(row * self.tile_height))
        widget.queue_resize()
        self.grid.queue_resize()
        self.grid.check_resize()
        if widget is self.tint2_slot:
            self.update_tint2_target_rect(int(x), int(row * self.tile_height), width, self.tile_height)

    def update_tint2_target_rect(self, x, y, width, height):
        gdk_window = self.win.get_window()
        if gdk_window is None:
            return
        origin = gdk_window.get_origin()
        origin_x, origin_y = origin[-2], origin[-1]
        self.tint2_slot.set_target_rect(origin_x + x, origin_y + y, width, height)

    def position_filter_entry(self, index=None, columns=None, column_offsets=None, column_widths=None):
        columns = max(1, int(columns or self.current_columns or self.layout_slot_count()))
        if index is None:
            for widget, layout_index, _span in self.iter_layout_positions(self.layout_entries(), columns):
                if widget is self.filter_entry:
                    index = layout_index
                    break
        index = self.layout_slot_count() - 1 if index is None else index
        self.position_widget_slot(self.filter_entry, index, columns, column_offsets, column_widths)

    def position_layout_entry(self, widget, index, span, columns, column_offsets=None, column_widths=None):
        if isinstance(widget, SimpleMirrorTile):
            column = index % columns
            row = index // columns
            if column_offsets is not None and column_widths is not None:
                width = column_widths[column]
                x = column_offsets[column]
            else:
                width = self.tile_width
                x = column * self.tile_width
            widget.set_layout_size(width, self.tile_height)
            self.grid.move(widget, int(x), int(row * self.tile_height))
            return
        self.position_widget_slot(widget, index, columns, column_offsets, column_widths, span)

    def position_layout_entries(self, entries, columns, column_offsets=None, column_widths=None):
        for widget, index, span in self.iter_layout_positions(entries, columns):
            self.position_layout_entry(widget, index, span, columns, column_offsets, column_widths)

    def add_tile(self, info):
        tile = SimpleMirrorTile(
            info,
            width=self.tile_width,
            height=self.tile_height,
            fps=self.fps,
            frame_interval_seconds=self.frame_interval_seconds,
            show_title=self.show_title,
            show_close=self.show_close,
            show_workspace=self.show_workspace,
            hover_mode=self.hover_mode,
            hover_scale=self.hover_scale,
            show_borders=self.show_borders,
            label_mode=self.label_mode,
            panel=self,
        )
        self.tiles.append(tile)
        self.grid.put(tile, 0, 0)
        self.current_columns = 0
        self.current_rows = 0
        tile.show_all()
        tile.set_visible(self.tile_matches_selection(tile) and self.tile_matches_filter(tile))
        return tile

    def tile_ids(self):
        return [tile.window_info.window_id for tile in self.tiles]

    def remove_tile(self, tile):
        if tile in self.tiles:
            self.tiles.remove(tile)
        self.grid.remove(tile)
        self.current_columns = 0
        self.current_rows = 0
        if self.hovered_tile is tile:
            self.hovered_tile = None
        tile.destroy()

    def reconcile_windows(self):
        try:
            windows = self.filter_windows(self.registry.list_windows())
        except RuntimeError:
            return True

        before_ids = [tile.window_info.window_id for tile in self.tiles]
        before_visible_ids = [tile.window_info.window_id for tile in self.visible_tiles()]
        next_by_id = {info.window_id: info for info in windows}
        existing_by_id = {tile.window_info.window_id: tile for tile in self.tiles}

        for tile in list(self.tiles):
            if tile.window_info.window_id not in next_by_id:
                self.remove_tile(tile)

        for info in windows:
            tile = existing_by_id.get(info.window_id)
            if tile is None:
                self.add_tile(info)
            else:
                tile.window_info = info
                tile.set_tooltip_text(info.title)

        self.apply_order()
        after_ids = [tile.window_info.window_id for tile in self.tiles]
        after_visible_ids = [tile.window_info.window_id for tile in self.visible_tiles()]
        if before_ids != after_ids or before_visible_ids != after_visible_ids:
            self.fit_tiles_to_window()
        return True

    def poll_active_window(self):
        active_window_id = self.registry.get_active_window_id()
        before_visible_ids = [tile.window_info.window_id for tile in self.visible_tiles()]
        self.active_window_id = active_window_id
        self.note_window_used(active_window_id)
        after_visible_ids = [tile.window_info.window_id for tile in self.visible_tiles()]
        if before_visible_ids != after_visible_ids:
            self.current_columns = 0
            self.current_rows = 0
            self.fit_tiles_to_window()
        return True

    def note_window_used(self, window_id, apply_order=True):
        if window_id is None:
            return
        window_id = int(window_id)
        if self.own_window_id is not None and window_id == self.own_window_id:
            return
        if window_id not in {tile.window_info.window_id for tile in self.tiles}:
            return
        if window_id in self.mru_window_ids:
            self.mru_window_ids.remove(window_id)
        self.mru_window_ids.insert(0, window_id)
        if apply_order and self.order_mode == "last-used":
            self.apply_order()

    def apply_order(self):
        if len(self.tiles) < 2:
            return
        before_ids = self.tile_ids()
        if self.order_mode == "name":
            self.tiles.sort(key=self.window_sort_key)
        elif self.order_mode == "last-used":
            mru_rank = {window_id: index for index, window_id in enumerate(self.mru_window_ids)}
            fallback_rank = {window_id: index for index, window_id in enumerate(before_ids)}
            self.tiles.sort(
                key=lambda tile: (
                    mru_rank.get(tile.window_info.window_id, len(self.tiles) + fallback_rank[tile.window_info.window_id]),
                    self.window_sort_key(tile),
                )
            )
        if self.tile_ids() != before_ids:
            self.current_columns = 0
            self.current_rows = 0
            self.fit_tiles_to_window()

    def window_sort_key(self, tile):
        info = tile.window_info
        title = (info.title or "").casefold()
        wm_class = (info.wm_class or "").casefold()
        return (title, wm_class, int(info.window_id))

    def choose_grid_shape(self, width, height, count):
        if count <= 1:
            return 1, 1
        width = max(1, int(width))
        height = max(1, int(height))
        best = None
        for columns in range(1, count + 1):
            rows = int(math.ceil(float(count) / columns))
            tile_width = max(1, width // columns)
            tile_height = max(1, height // rows)
            visible_area = min(tile_width, MAX_TILE_WIDTH) * min(tile_height, MAX_TILE_HEIGHT)
            aspect = float(tile_width) / max(1.0, float(tile_height))
            aspect_penalty = abs(math.log(max(0.1, aspect / 1.6)))
            empty_slots = (columns * rows) - count
            score = visible_area - (visible_area * aspect_penalty * 0.18) - (empty_slots * 40)
            if best is None or score > best[0]:
                best = (score, columns, rows)
        return best[1], best[2]

    def relayout_tiles(self, columns, rows):
        columns = max(1, int(columns))
        entries = self.layout_entries()
        rows = max(1, int(rows), self.layout_rows_for_entries(entries, columns))
        self.current_columns = columns
        self.current_rows = rows
        visible_tiles = self.visible_tiles()
        for tile in visible_tiles:
            if tile.get_parent() is None:
                self.grid.put(tile, 0, 0)
            tile.show()
        for tile in self.tiles:
            tile.set_visible(tile in visible_tiles)
        for slot in self.utility_slots():
            slot.set_visible(True)
        self.clock_slot.set_visible(self.show_clock)
        self.tint2_slot.set_visible(self.show_tint2)
        self.position_layout_entries(entries, columns)
        self.grid.queue_resize()
        self.win.queue_resize()

    def fit_tiles_to_window(self):
        visible_tiles = self.visible_tiles()
        if not visible_tiles:
            for tile in self.tiles:
                tile.set_visible(False)
        alloc = self.grid.get_allocation()
        if alloc.width <= 1 or alloc.height <= 1:
            alloc = self.win.get_allocation()
        width = alloc.width
        height = alloc.height
        if width <= 1 or height <= 1:
            return
        entries = self.layout_entries()
        slot_count = sum(units for _widget, units in entries)
        columns, rows = self.choose_grid_shape(width, height, slot_count)
        rows = self.layout_rows_for_entries(entries, columns)
        target_width = clamp(width // columns, MIN_TILE_WIDTH, MAX_TILE_WIDTH, self.tile_width)
        target_height = clamp(height // rows, MIN_TILE_HEIGHT, MAX_TILE_HEIGHT, self.tile_height)
        self.tile_width = target_width
        self.tile_height = target_height
        for tile in visible_tiles:
            tile.set_dimensions(self.tile_width, self.tile_height)
        self.relayout_tiles(columns, rows)
        self.apply_tile_size_requests()

    def set_hovered_tile(self, tile):
        next_tile = tile if tile in self.visible_tiles() and self.hover_expand and self.hover_scale > 1.0 else None
        if self.hovered_tile is next_tile:
            return
        self.hovered_tile = next_tile
        self.apply_tile_size_requests()

    def on_panel_enter(self, *_args):
        self.note_pointer_inside(True)
        return False

    def on_panel_leave(self, *_args):
        self.note_pointer_inside(False)
        return False

    def note_pointer_inside(self, inside):
        self.pointer_inside_panel = bool(inside)
        if self.pointer_inside_panel:
            self.restore_from_idle()
            return
        self.schedule_idle_mode()

    def schedule_idle_mode(self):
        if self.idle_mode == "off":
            return
        if self.idle_source_id is not None:
            GLib.source_remove(self.idle_source_id)
        self.idle_source_id = GLib.timeout_add(self.idle_delay_ms, self.apply_idle_mode)

    def apply_idle_mode(self):
        self.idle_source_id = None
        if self.pointer_inside_panel or self.idle_mode == "off":
            return False
        if self.idle_mode == "collapse":
            self.collapse_for_idle()
        elif self.idle_mode == "hide":
            self.hide_for_idle()
        return False

    def collapse_for_idle(self):
        if self.collapsed:
            return
        self.restore_size = self.win.get_size()
        for tile in self.tiles:
            tile.release_layout_size()
        self.collapsed = True
        width = max(80, self.restore_size[0]) if self.restore_size else 240
        self.win.resize(width, 10)

    def hide_for_idle(self):
        if self.hidden_by_idle:
            return
        x, y = self.win.get_position()
        width, height = self.win.get_size()
        self.restore_rect = (x, y, max(1, width), max(1, height))
        self.hidden_by_idle = True
        self.win.hide()
        if self.hidden_poll_source_id is None:
            self.hidden_poll_source_id = GLib.timeout_add(160, self.poll_hidden_restore)

    def poll_hidden_restore(self):
        if not self.hidden_by_idle:
            self.hidden_poll_source_id = None
            return False
        if self.restore_rect is None:
            return True
        pointer = self.get_pointer_position()
        if pointer is None:
            return True
        x, y, width, height = self.restore_rect
        px, py = pointer
        if x <= px <= x + width and y <= py <= y + height:
            self.restore_from_idle()
            self.hidden_poll_source_id = None
            return False
        return True

    def get_pointer_position(self):
        display = Gdk.Display.get_default()
        if display is None:
            return None
        seat = display.get_default_seat()
        if seat is None:
            return None
        pointer = seat.get_pointer()
        if pointer is None:
            return None
        _screen, x, y = pointer.get_position()
        return x, y

    def restore_from_idle(self):
        if self.idle_source_id is not None:
            GLib.source_remove(self.idle_source_id)
            self.idle_source_id = None
        if self.hidden_by_idle:
            self.hidden_by_idle = False
            if self.restore_rect is not None:
                x, y, width, height = self.restore_rect
                self.win.move(x, y)
                self.win.resize(width, height)
            self.win.show_all()
        if self.collapsed:
            self.collapsed = False
            if self.restore_size is not None:
                self.win.resize(max(1, self.restore_size[0]), max(1, self.restore_size[1]))
        self.fit_tiles_to_window()

    def apply_tile_size_requests(self):
        visible_tiles = self.visible_tiles()
        entries = self.layout_entries()
        slot_count = sum(units for _widget, units in entries)
        columns = max(1, self.current_columns or slot_count)
        rows = max(1, self.current_rows or self.layout_rows_for_entries(entries, columns))
        alloc = self.grid.get_allocation()
        if alloc.width <= 1:
            alloc = self.win.get_allocation()
        total_width = max(1, alloc.width)

        if self.hovered_tile not in visible_tiles or self.hover_scale <= 1.0:
            self.clock_slot.set_visible(self.show_clock)
            self.tint2_slot.set_visible(self.show_tint2)
            self.position_layout_entries(entries, columns)
            self.grid.queue_resize()
            return

        column_weights = [1.0 for _index in range(columns)]
        hover_index = visible_tiles.index(self.hovered_tile)
        hover_column = hover_index % columns
        column_weights[hover_column] = self.hover_scale
        column_widths = self.distribute_pixels(total_width, column_weights)
        column_offsets = [0]
        for width in column_widths[:-1]:
            column_offsets.append(column_offsets[-1] + width)

        self.clock_slot.set_visible(self.show_clock)
        self.tint2_slot.set_visible(self.show_tint2)
        self.position_layout_entries(entries, columns, column_offsets, column_widths)
        self.grid.queue_resize()

    def distribute_pixels(self, total, weights):
        total = max(1, int(total))
        weight_sum = max(0.001, sum(weights))
        raw_sizes = [float(total) * (weight / weight_sum) for weight in weights]
        sizes = [max(1, int(math.floor(size))) for size in raw_sizes]
        remainder = total - sum(sizes)
        fractions = sorted(
            range(len(raw_sizes)),
            key=lambda index: raw_sizes[index] - math.floor(raw_sizes[index]),
            reverse=True,
        )
        step = 1 if remainder >= 0 else -1
        for index in fractions:
            if remainder == 0:
                break
            if step < 0 and sizes[index] <= 1:
                continue
            sizes[index] += step
            remainder -= step
        return sizes

    def event_position_in_panel(self, event):
        gdk_window = self.win.get_window()
        if gdk_window is None:
            return event.x, event.y
        origin = gdk_window.get_origin()
        origin_x, origin_y = origin[-2], origin[-1]
        return event.x_root - origin_x, event.y_root - origin_y

    def widget_contains_panel_point(self, widget, x, y):
        translated = widget.translate_coordinates(self.win, 0, 0)
        if translated is None:
            return False
        widget_x, widget_y = translated
        alloc = widget.get_allocation()
        return widget_x <= x < widget_x + alloc.width and widget_y <= y < widget_y + alloc.height

    def tile_at_panel_point(self, x, y):
        for tile in self.visible_tiles():
            if self.widget_contains_panel_point(tile, x, y):
                return tile
        return None

    def on_panel_button_press(self, _widget, event):
        x, y = self.event_position_in_panel(event)
        if self.widget_contains_panel_point(self.filter_entry, x, y):
            return False
        tile = self.tile_at_panel_point(x, y)
        if int(event.button) == 3:
            self.show_context_menu(event, tile)
            return True
        if int(event.button) == 1 and tile is not None:
            tile.activate_window()
            return True
        return False

    def show_context_menu(self, event, tile):
        menu = Gtk.Menu()

        self.add_check_item(menu, "Mostrar nombre", self.show_title, lambda active: self.update_options(show_title=active))
        self.add_check_item(menu, "Mostrar cerrar", self.show_close, lambda active: self.update_options(show_close=active))
        self.add_check_item(menu, "Mostrar workspace", self.show_workspace, lambda active: self.update_options(show_workspace=active))
        self.add_check_item(menu, "Mostrar bordes", self.show_borders, lambda active: self.update_options(show_borders=active))
        selector_item = Gtk.MenuItem(label="Seleccionar ventanas...")
        selector_item.connect("activate", lambda *_args: self.show_window_selector())
        menu.append(selector_item)
        self.add_check_item(menu, "Editar orden", self.order_edit_mode, self.set_order_edit_mode)
        menu.append(Gtk.SeparatorMenuItem())

        clock_menu = Gtk.Menu()
        self.add_check_item(clock_menu, "Mostrar hora/fecha", self.show_clock, self.set_show_clock)
        clock_menu.append(Gtk.SeparatorMenuItem())
        clock_group = None
        for label, mode in (("Hora", "time"), ("Hora con segundos", "time-seconds"), ("Fecha y hora", "date-time"), ("Completo", "full")):
            item = Gtk.RadioMenuItem.new_with_label_from_widget(clock_group, label)
            if clock_group is None:
                clock_group = item
            item.set_active(self.clock_mode == mode)
            item.connect("toggled", lambda check, value=mode: check.get_active() and self.set_clock_mode(value))
            clock_menu.append(item)
        clock_item = Gtk.MenuItem(label="Hora y fecha")
        clock_item.set_submenu(clock_menu)
        menu.append(clock_item)

        terminal_menu = Gtk.Menu()
        add_terminal_item = Gtk.MenuItem(label="Agregar mini terminal")
        add_terminal_item.connect("activate", lambda *_args: self.add_terminal_slot())
        terminal_menu.append(add_terminal_item)
        remove_terminal_item = Gtk.MenuItem(label="Quitar ultima")
        remove_terminal_item.set_sensitive(bool(self.terminal_slots))
        remove_terminal_item.connect("activate", lambda *_args: self.remove_terminal_slot())
        terminal_menu.append(remove_terminal_item)
        remove_all_terminal_item = Gtk.MenuItem(label="Quitar todas")
        remove_all_terminal_item.set_sensitive(bool(self.terminal_slots))
        remove_all_terminal_item.connect("activate", lambda *_args: self.clear_terminal_slots())
        terminal_menu.append(remove_all_terminal_item)
        terminal_item = Gtk.MenuItem(label=f"Mini terminales ({len(self.terminal_slots)})")
        terminal_item.set_submenu(terminal_menu)
        menu.append(terminal_item)

        executor_menu = Gtk.Menu()
        add_executor_item = Gtk.MenuItem(label="Agregar ejecutor")
        add_executor_item.connect("activate", lambda *_args: self.add_executor_slot())
        executor_menu.append(add_executor_item)
        remove_executor_item = Gtk.MenuItem(label="Quitar ultimo")
        remove_executor_item.set_sensitive(bool(self.executor_slots))
        remove_executor_item.connect("activate", lambda *_args: self.remove_executor_slot())
        executor_menu.append(remove_executor_item)
        remove_all_executor_item = Gtk.MenuItem(label="Quitar todos")
        remove_all_executor_item.set_sensitive(bool(self.executor_slots))
        remove_all_executor_item.connect("activate", lambda *_args: self.clear_executor_slots())
        executor_menu.append(remove_all_executor_item)
        executor_item = Gtk.MenuItem(label=f"Ejecutores ({len(self.executor_slots)})")
        executor_item.set_submenu(executor_menu)
        menu.append(executor_item)

        tint2_menu = Gtk.Menu()
        self.add_check_item(tint2_menu, "Mostrar tint2", self.show_tint2, self.set_show_tint2)
        tint2_menu.append(Gtk.SeparatorMenuItem())
        tint2_group = None
        for label, profile in (("Default compacto", "default"), ("Chema compacto", "chema-compact")):
            item = Gtk.RadioMenuItem.new_with_label_from_widget(tint2_group, label)
            if tint2_group is None:
                tint2_group = item
            item.set_active(self.tint2_profile == profile)
            item.connect("toggled", lambda check, value=profile: check.get_active() and self.set_tint2_profile(value))
            tint2_menu.append(item)
        restart_tint2_item = Gtk.MenuItem(label="Reiniciar tint2")
        restart_tint2_item.set_sensitive(self.show_tint2)
        restart_tint2_item.connect("activate", lambda *_args: self.restart_tint2_slot())
        tint2_menu.append(restart_tint2_item)
        tint2_item = Gtk.MenuItem(label="Tint2")
        tint2_item.set_submenu(tint2_menu)
        menu.append(tint2_item)

        menu.append(Gtk.SeparatorMenuItem())

        order_menu = Gtk.Menu()
        for label, mode in (("Ultima app usada", "last-used"), ("Nombre", "name"), ("Manual", "manual")):
            item = Gtk.RadioMenuItem.new_with_label_from_widget(
                order_menu.get_children()[0] if order_menu.get_children() else None,
                label,
            )
            item.set_active(self.order_mode == mode)
            item.connect("toggled", lambda check, value=mode: check.get_active() and self.set_order_mode(value))
            order_menu.append(item)
        order_item = Gtk.MenuItem(label="Orden")
        order_item.set_submenu(order_menu)
        menu.append(order_item)

        hover_menu = Gtk.Menu()
        for label, mode in (("Sin agrandar", "off"), ("Suave", "soft"), ("Medio", "medium"), ("Grande", "large")):
            item = Gtk.RadioMenuItem.new_with_label_from_widget(
                hover_menu.get_children()[0] if hover_menu.get_children() else None,
                label,
            )
            item.set_active(self.hover_mode == mode)
            item.connect("toggled", lambda check, value=mode: check.get_active() and self.update_options(hover_mode=value))
            hover_menu.append(item)
        hover_menu.append(Gtk.SeparatorMenuItem())
        reduce_item = Gtk.MenuItem(label="Disminuir efecto")
        reduce_item.connect("activate", lambda *_args: self.adjust_hover_scale(-0.1))
        hover_menu.append(reduce_item)
        increase_item = Gtk.MenuItem(label="Aumentar efecto")
        increase_item.connect("activate", lambda *_args: self.adjust_hover_scale(0.1))
        hover_menu.append(increase_item)
        hover_menu.append(Gtk.SeparatorMenuItem())
        for label, scale in (("Efecto 125%", 1.25), ("Efecto 150%", 1.5), ("Efecto 200%", 2.0)):
            item = Gtk.MenuItem(label=label)
            item.connect("activate", lambda _item, value=scale: self.set_hover_scale(value))
            hover_menu.append(item)
        hover_item = Gtk.MenuItem(label="Agrandar al pasar")
        hover_item.set_submenu(hover_menu)
        menu.append(hover_item)

        size_menu = Gtk.Menu()
        self.add_size_item(size_menu, "Pequeno", 80, 48)
        self.add_size_item(size_menu, "Normal", DEFAULT_TILE_WIDTH, DEFAULT_TILE_HEIGHT)
        self.add_size_item(size_menu, "Grande", 160, 96)
        size_item = Gtk.MenuItem(label="Tamano")
        size_item.set_submenu(size_menu)
        menu.append(size_item)

        fps_menu = Gtk.Menu()
        for fps in (0, 1, 4, 8, 12):
            label = "0 FPS (pausado)" if fps == 0 else f"{fps} FPS"
            item = Gtk.MenuItem(label=label)
            item.connect("activate", lambda _item, value=fps: self.set_fps(value))
            fps_menu.append(item)
        fps_menu.append(Gtk.SeparatorMenuItem())
        for seconds in (2, 5, 10, 30, 60):
            item = Gtk.MenuItem(label=f"1 frame cada {seconds}s")
            item.connect("activate", lambda _item, value=seconds: self.set_frame_interval_seconds(value))
            fps_menu.append(item)
        fps_item = Gtk.MenuItem(label="FPS")
        fps_item.set_submenu(fps_menu)
        menu.append(fps_item)

        label_menu = Gtk.Menu()
        for label, mode in (("Titulo de ventana", "title"), ("App / ejecutable", "app")):
            item = Gtk.RadioMenuItem.new_with_label_from_widget(
                label_menu.get_children()[0] if label_menu.get_children() else None,
                label,
            )
            item.set_active(self.label_mode == mode)
            item.connect("toggled", lambda check, value=mode: check.get_active() and self.update_options(label_mode=value))
            label_menu.append(item)
        label_item = Gtk.MenuItem(label="Texto mostrado")
        label_item.set_submenu(label_menu)
        menu.append(label_item)

        idle_menu = Gtk.Menu()
        for label, mode in (("Siempre visible", "off"), ("Reducir sin cursor", "collapse"), ("Ocultar sin cursor", "hide")):
            item = Gtk.RadioMenuItem.new_with_label_from_widget(
                idle_menu.get_children()[0] if idle_menu.get_children() else None,
                label,
            )
            item.set_active(self.idle_mode == mode)
            item.connect("toggled", lambda check, value=mode: check.get_active() and self.set_idle_mode(value))
            idle_menu.append(item)
        idle_item = Gtk.MenuItem(label="Sin cursor")
        idle_item.set_submenu(idle_menu)
        menu.append(idle_item)

        menu.append(Gtk.SeparatorMenuItem())
        refresh_item = Gtk.MenuItem(label="Actualizar ahora")
        refresh_item.connect("activate", lambda *_args: self.refresh_all_tiles())
        menu.append(refresh_item)

        if tile is not None:
            exclude_item = Gtk.MenuItem(label="Excluir esta ventana")
            exclude_item.connect("activate", lambda *_args: self.exclude_window(tile))
            menu.append(exclude_item)

            close_window_item = Gtk.MenuItem(label="Cerrar esta ventana")
            close_window_item.connect("activate", lambda *_args: tile.close_window())
            menu.append(close_window_item)

        if self.excluded_window_ids:
            restore_item = Gtk.MenuItem(label="Mostrar ventanas excluidas")
            restore_item.connect("activate", lambda *_args: self.restore_excluded_windows())
            menu.append(restore_item)

        close_bar_item = Gtk.MenuItem(label="Cerrar barra")
        close_bar_item.connect("activate", lambda *_args: self.win.destroy())
        menu.append(close_bar_item)

        menu.show_all()
        menu.popup_at_pointer(event)

    def add_check_item(self, menu, label, active, callback):
        item = Gtk.CheckMenuItem(label=label)
        item.set_active(bool(active))
        item.connect("toggled", lambda check: callback(check.get_active()))
        menu.append(item)

    def add_size_item(self, menu, label, width, height):
        item = Gtk.MenuItem(label=f"{label} ({width}x{height})")
        item.connect("activate", lambda *_args: self.set_tile_size(width, height))
        menu.append(item)

    def set_order_edit_mode(self, active):
        self.order_edit_mode = bool(active)
        if self.order_edit_mode:
            self.set_order_mode("manual", apply_order=False)
        for tile in self.tiles:
            tile.queue_draw()

    def set_order_mode(self, mode, apply_order=True):
        self.order_mode = normalize_order_mode(mode)
        if self.order_mode == "manual":
            self.order_edit_mode = True
        else:
            self.order_edit_mode = False
        if apply_order:
            self.apply_order()
        for tile in self.tiles:
            tile.queue_draw()

    def set_idle_mode(self, mode):
        self.idle_mode = normalize_idle_mode(mode)
        if self.idle_mode == "off":
            self.restore_from_idle()
        elif not self.pointer_inside_panel:
            self.schedule_idle_mode()

    def set_show_clock(self, active):
        self.show_clock = bool(active)
        self.clock_slot.set_visible(self.show_clock)
        self.update_clock_timer()
        self.current_columns = 0
        self.current_rows = 0
        self.fit_tiles_to_window()

    def set_clock_mode(self, mode):
        self.clock_mode = normalize_clock_mode(mode)
        self.clock_slot.set_mode(self.clock_mode)
        self.update_clock_timer()

    def set_show_tint2(self, active):
        self.show_tint2 = bool(active)
        self.tint2_slot.set_visible(self.show_tint2)
        if self.show_tint2:
            self.tint2_slot.start()
        else:
            self.tint2_slot.stop()
        self.current_columns = 0
        self.current_rows = 0
        self.fit_tiles_to_window()

    def set_tint2_profile(self, profile):
        self.tint2_profile = normalize_tint2_profile(profile)
        self.tint2_slot.set_profile(self.tint2_profile)
        self.current_columns = 0
        self.current_rows = 0
        self.fit_tiles_to_window()

    def restart_tint2_slot(self):
        if not self.show_tint2:
            return
        self.tint2_slot.restart()
        self.fit_tiles_to_window()

    def update_clock_timer(self):
        if self.clock_source_id is not None:
            GLib.source_remove(self.clock_source_id)
            self.clock_source_id = None
        if not self.show_clock:
            return
        interval = 1000 if self.clock_mode in {"time-seconds", "full"} else 30000
        self.clock_source_id = GLib.timeout_add(interval, self.refresh_clock)

    def refresh_clock(self):
        self.clock_slot.queue_draw()
        return self.show_clock

    def add_terminal_slot(self):
        slot = MiniTerminalSlot()
        self.terminal_slots.append(slot)
        self.grid.put(slot, 0, 0)
        slot.show_all()
        self.current_columns = 0
        self.current_rows = 0
        self.fit_tiles_to_window()

    def remove_terminal_slot(self):
        if not self.terminal_slots:
            return
        slot = self.terminal_slots.pop()
        self.grid.remove(slot)
        slot.destroy()
        self.current_columns = 0
        self.current_rows = 0
        self.fit_tiles_to_window()

    def clear_terminal_slots(self):
        while self.terminal_slots:
            slot = self.terminal_slots.pop()
            self.grid.remove(slot)
            slot.destroy()
        self.current_columns = 0
        self.current_rows = 0
        self.fit_tiles_to_window()

    def add_executor_slot(self):
        slot = CommandRunnerSlot()
        self.executor_slots.append(slot)
        self.grid.put(slot, 0, 0)
        slot.show_all()
        self.current_columns = 0
        self.current_rows = 0
        self.fit_tiles_to_window()

    def remove_executor_slot(self):
        if not self.executor_slots:
            return
        slot = self.executor_slots.pop()
        self.grid.remove(slot)
        slot.destroy()
        self.current_columns = 0
        self.current_rows = 0
        self.fit_tiles_to_window()

    def clear_executor_slots(self):
        while self.executor_slots:
            slot = self.executor_slots.pop()
            self.grid.remove(slot)
            slot.destroy()
        self.current_columns = 0
        self.current_rows = 0
        self.fit_tiles_to_window()

    def set_selected_window_ids(self, window_ids):
        selected = {int(window_id) for window_id in window_ids}
        current_ids = {int(tile.window_info.window_id) for tile in self.tiles}
        self.selected_window_ids = None if selected == current_ids else selected
        self.hovered_tile = None
        self.current_columns = 0
        self.current_rows = 0
        self.fit_tiles_to_window()

    def show_window_selector(self):
        self.reconcile_windows()
        dialog = Gtk.Dialog(title="Seleccionar ventanas", transient_for=self.win, modal=True)
        dialog.add_button("Cancelar", Gtk.ResponseType.CANCEL)
        dialog.add_button("Aplicar", Gtk.ResponseType.OK)
        dialog.set_default_size(520, 420)

        content = dialog.get_content_area()
        summary = Gtk.Label(label=f"Ventanas detectadas: {len(self.tiles)}")
        summary.set_xalign(0.0)
        summary.set_margin_start(10)
        summary.set_margin_end(10)
        summary.set_margin_top(10)
        summary.set_margin_bottom(6)
        content.pack_start(summary, False, False, 0)

        button_row = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=6)
        button_row.set_margin_start(10)
        button_row.set_margin_end(10)
        button_row.set_margin_bottom(8)
        select_all_button = Gtk.Button(label="Todas")
        select_none_button = Gtk.Button(label="Ninguna")
        button_row.pack_start(select_all_button, False, False, 0)
        button_row.pack_start(select_none_button, False, False, 0)
        content.pack_start(button_row, False, False, 0)

        scroller = Gtk.ScrolledWindow()
        scroller.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)
        scroller.set_vexpand(True)
        scroller.set_margin_start(10)
        scroller.set_margin_end(10)
        scroller.set_margin_bottom(10)
        list_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=4)
        scroller.add(list_box)
        content.pack_start(scroller, True, True, 0)

        checks = []
        selected = self.selected_window_ids
        for tile in sorted(self.tiles, key=self.window_sort_key):
            info = tile.window_info
            label = f"{app_name_from_wm_class(info.wm_class)} - {info.title or info.window_hex}"
            check = Gtk.CheckButton(label=label)
            check.set_tooltip_text(f"{info.window_hex}  {info.wm_class}")
            check.set_active(selected is None or int(info.window_id) in selected)
            check.set_margin_start(4)
            check.set_margin_end(4)
            list_box.pack_start(check, False, False, 0)
            checks.append((check, int(info.window_id)))

        select_all_button.connect("clicked", lambda *_args: [check.set_active(True) for check, _window_id in checks])
        select_none_button.connect("clicked", lambda *_args: [check.set_active(False) for check, _window_id in checks])

        dialog.show_all()
        response = dialog.run()
        if response == Gtk.ResponseType.OK:
            self.set_selected_window_ids(window_id for check, window_id in checks if check.get_active())
        dialog.destroy()

    def move_tile(self, tile, delta):
        if tile not in self.tiles or not self.tiles:
            return
        old_index = self.tiles.index(tile)
        new_index = max(0, min(len(self.tiles) - 1, old_index + int(delta)))
        if new_index == old_index:
            return
        self.set_order_mode("manual", apply_order=False)
        self.tiles.pop(old_index)
        self.tiles.insert(new_index, tile)
        self.current_columns = 0
        self.current_rows = 0
        self.fit_tiles_to_window()
        for item in self.tiles:
            item.queue_draw()

    def update_options(
        self,
        show_title=None,
        show_close=None,
        show_workspace=None,
        hover_expand=None,
        hover_mode=None,
        hover_scale=None,
        show_borders=None,
        label_mode=None,
    ):
        if show_title is not None:
            self.show_title = bool(show_title)
        if show_close is not None:
            self.show_close = bool(show_close)
        if show_workspace is not None:
            self.show_workspace = bool(show_workspace)
        if hover_mode is not None or hover_expand is not None:
            self.hover_mode = normalize_hover_mode(hover_mode, hover_expand if hover_expand is not None else self.hover_expand)
            self.hover_expand = self.hover_mode != "off"
            if hover_scale is None:
                self.hover_scale = normalize_hover_scale(None, self.hover_mode, self.hover_expand)
        if hover_scale is not None:
            self.hover_scale = normalize_hover_scale(hover_scale, self.hover_mode, self.hover_expand)
            self.hover_expand = self.hover_scale > 1.0
            if self.hover_scale <= 1.0:
                self.hover_mode = "off"
        if show_borders is not None:
            self.show_borders = bool(show_borders)
        if label_mode is not None:
            self.label_mode = normalize_label_mode(label_mode)
        for tile in self.tiles:
            tile.set_display_options(
                show_title=self.show_title,
                show_close=self.show_close,
                show_workspace=self.show_workspace,
                hover_mode=self.hover_mode,
                hover_scale=self.hover_scale,
                show_borders=self.show_borders,
                label_mode=self.label_mode,
            )
        if not self.hover_expand or self.hover_scale <= 1.0:
            self.hovered_tile = None
        self.apply_tile_size_requests()

    def set_hover_scale(self, scale):
        self.update_options(hover_scale=scale)

    def adjust_hover_scale(self, delta):
        self.set_hover_scale(self.hover_scale + float(delta))

    def set_tile_size(self, width, height):
        self.tile_width = clamp(width, MIN_TILE_WIDTH, MAX_TILE_WIDTH, DEFAULT_TILE_WIDTH)
        self.tile_height = clamp(height, MIN_TILE_HEIGHT, MAX_TILE_HEIGHT, DEFAULT_TILE_HEIGHT)
        for tile in self.tiles:
            tile.set_dimensions(self.tile_width, self.tile_height)
        self.fit_tiles_to_window()

    def set_fps(self, fps):
        self.fps = max(0.0, min(12.0, float(fps)))
        self.frame_interval_seconds = None
        for tile in self.tiles:
            tile.set_fps(self.fps)

    def set_frame_interval_seconds(self, seconds):
        self.frame_interval_seconds = seconds
        for tile in self.tiles:
            tile.set_frame_interval_seconds(seconds)

    def refresh_all_tiles(self):
        for tile in self.tiles:
            tile.refresh()

    def exclude_window(self, tile):
        self.excluded_window_ids.add(int(tile.window_info.window_id))
        self.remove_tile(tile)
        self.current_columns = 0
        self.current_rows = 0
        self.fit_tiles_to_window()

    def restore_excluded_windows(self):
        self.excluded_window_ids.clear()
        self.reconcile_windows()

    def on_configure_event(self, *_args):
        self.fit_tiles_to_window()
        for tile in self.tiles:
            tile.queue_draw()
        return False

    def on_destroy(self, *_args):
        if self.window_refresh_source_id is not None:
            GLib.source_remove(self.window_refresh_source_id)
            self.window_refresh_source_id = None
        if self.active_window_source_id is not None:
            GLib.source_remove(self.active_window_source_id)
            self.active_window_source_id = None
        if self.idle_source_id is not None:
            GLib.source_remove(self.idle_source_id)
            self.idle_source_id = None
        if self.hidden_poll_source_id is not None:
            GLib.source_remove(self.hidden_poll_source_id)
            self.hidden_poll_source_id = None
        if self.clock_source_id is not None:
            GLib.source_remove(self.clock_source_id)
            self.clock_source_id = None
        self.tint2_slot.stop()
        if Gtk.main_level() > 0:
            Gtk.main_quit()

    def on_key_press(self, _win, event):
        key = Gdk.keyval_name(event.keyval)
        if key == "Escape":
            Gtk.main_quit()
            return True
        if key in ("q", "Q") and (event.state & Gdk.ModifierType.CONTROL_MASK):
            Gtk.main_quit()
            return True
        return False
